Document: libbroadvoice
Title: Debian libbroadvoice Manual
Author: <insert document author here>
Abstract: This manual describes what libbroadvoice is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libbroadvoice/libbroadvoice.sgml.gz

Format: postscript
Files: /usr/share/doc/libbroadvoice/libbroadvoice.ps.gz

Format: text
Files: /usr/share/doc/libbroadvoice/libbroadvoice.text.gz

Format: HTML
Index: /usr/share/doc/libbroadvoice/html/index.html
Files: /usr/share/doc/libbroadvoice/html/*.html
